import "./globals.css";
import {Roboto} from "next/font/google"

export const metadata = {
  title: "Landrup Dans",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
