import "./globals.css";

export const metadata = {
  title: "Landrup Dans",
  description: "Generated by create next app",
};

// const racing_sans = Racing({
//   subsets: ['latin'],
//   weight: ['900'],
//   variable: '--font-racing-sans-one',
// })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
